{% set version = '1.0.11' %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-robstattm
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/RobStatTM_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/RobStatTM/RobStatTM_{{ version }}.tar.gz
  sha256: da89c98a76fb2d8c4cd5c54a98eccf57e7ddaf67ae355e235ae93f2e1610901a

build:
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/
  missing_dso_whitelist:
    - '*/R.dll'        # [win]
    - '*/Rblas.dll'    # [win]
    - '*/Rlapack.dll'  # [win]

requirements:
  build:
    - {{ compiler('c') }}              # [not win]
    - {{ stdlib('c') }}                # [not win]
    - {{ compiler('m2w64_c') }}        # [win]
    - {{ stdlib('m2w64_c') }}          # [win]
    - {{ compiler('fortran') }}        # [not win]
    - {{ compiler('m2w64_fortran') }}  # [win]
    - {{ posix }}filesystem        # [win]
    - {{ posix }}make
    - {{ posix }}sed               # [win]
    - {{ posix }}coreutils         # [win]
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - libblas
    - liblapack
    - r-base
    - r-pyinit
    - r-robustbase
    - r-rrcov
  run:
    - r-base
    - r-pyinit
    - r-robustbase
    - r-rrcov

test:
  commands:
    - $R -e "library('RobStatTM')"           # [not win]
    - "\"%R%\" -e \"library('RobStatTM')\""  # [win]

about:
  home: https://CRAN.R-project.org/package=RobStatTM
  license: GPL-3.0-or-later
  summary: 'Companion package for the book: "Robust Statistics: Theory and Methods, second edition",
    <http://www.wiley.com/go/maronna/robust>.  This package contains code that implements
    the robust estimators discussed in the recent second edition of the book above,
    as well as the scripts reproducing all the examples in the book.'
  license_family: GPL3
  license_file:
    - '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3'

extra:
  recipe-maintainers:
    - conda-forge/r
